# Generated by Django 4.2.21 on 2025-05-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('portfolio', 'Portfolio'), ('ecommerce', 'E-commerce'), ('business', 'Business'), ('landing-page', 'Landing Page')], max_length=50),
        ),
    ]
