# Generated by Django 4.2.21 on 2025-05-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_template_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Average rating (0.0 to 5.0)'),
        ),
        migrations.AddField(
            model_name='template',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of ratings'),
        ),
        migrations.AddField(
            model_name='template',
            name='technologies',
            field=models.CharField(blank=True, help_text='e.g., HTML CSS JS BOOTSTRAP', max_length=100),
        ),
    ]
