# Generated by Django 4.2.21 on 2025-05-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_template_rating_template_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('portfolio', 'Portfolio'), ('ecommerce', 'E-commerce'), ('business', 'Business'), ('landing-page', 'Landing Page')], max_length=20),
        ),
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='template',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='template',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='template',
            name='technologies',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
