# Generated by Django 4.2.21 on 2025-06-01 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_template_category_alter_template_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='features',
            field=models.TextField(blank=True, help_text="JSON format: [{'name': 'Feature', 'description': 'Description', 'icon': 'bi bi-icon'}]"),
        ),
        migrations.AddField(
            model_name='template',
            name='why_choose',
            field=models.TextField(blank=True, help_text='Why choose this template?'),
        ),
        migrations.CreateModel(
            name='TemplateScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='templates/screenshots/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='admin_panel.template')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='admin_panel.template')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='admin_panel.template')),
            ],
        ),
    ]
