# Generated by Django 4.2.21 on 2025-06-01 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_template_features_template_why_choose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='features',
        ),
        migrations.RemoveField(
            model_name='template',
            name='image',
        ),
        migrations.CreateModel(
            name='TemplateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='templates/images/')),
                ('alt_text', models.CharField(blank=True, max_length=100)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admin_panel.template')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="Bootstrap icon class, e.g., 'bi bi-display'", max_length=50)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='admin_panel.template')),
            ],
        ),
    ]
