# Generated by Django 4.2.21 on 2025-06-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='templatescreenshot',
            name='image',
            field=models.ImageField(upload_to='screenshots/'),
        ),
    ]
