# Generated by Django 4.2.21 on 2025-06-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_alter_templateimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text')], default='video', max_length=20),
        ),
    ]
