# Generated by Django 4.2.21 on 2025-06-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_tutorial_content_tutorial_level_tutorial_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='installation_instructions',
            field=models.TextField(blank=True, help_text='Instructions to install and run this template'),
        ),
        migrations.AddField(
            model_name='template',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Upload the ZIP file for this template', null=True, upload_to='templates/zips/'),
        ),
    ]
